version: "3.8"

services:

  #----Gateway----
  gateway:
    build: ./services/Gateway
    ports:
      - "8080:8080"
    environment:
      - EUREKA_URL=http://eureka:8761/eureka
    networks:
      - net

  #----Eureka----
  eureka:
    container_name: eureka
    build: ./services/Eureka
    ports:
      - "8761:8761"
    networks:
      - net
  #----Schedule----
  schedule-service:
    restart: always
    build:
      context: ./services/schedule/
    # deploy:
    #   mode: replicated
    #   replicas: 3
    #   resources:
    #     limits:
    #       cpus: "0.25"
    #       memory: 128M
    #     reservations:
    #       memory: 64M
    links:
      - mongo
    depends_on:
      - mongo
      - eureka
    networks:
      - net

  #----Mongo----
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 128M
        reservations:
          memory: 64M
    ports:
      - "8989:27017"
    networks:
      - net

networks:
  net:
    driver: bridge